name: Push Overleaf PDF to Github Pages.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update the index.html
        run: |
          sed -E -i "s|github.com/([^/]+)/raw|github.com/${{ github.repository }}/raw|g" index.html
          sed -E -i "s|main/([^_]+)_resume.pdf|main/kapila_nikhil_resume.pdf|g" index.html
              
      - name: Commit and push PDF file
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add .
          git commit -m "Add ${{ secrets.ACTOR }}_resume.pdf"
          git push origin main
